import Head from "next/head";
import Menu from "../components/Menu/Menu";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { getSortedPostsData } from "../../lib/posts";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu allPostData={allPostsData} />
      <main>
        <section>
          <h2>Blog</h2>
          {/* <ul>
            {allPostsData.map(
              ({ id, date, title, description, tags, type }) => (
                <li key={id}>{title}</li>
              )
            )}
          </ul> */}
        </section>
      </main>
    </>
  );
}
