import Head from "next/head";
import Menu from "../components/Menu/Menu";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { getSortedPostsData } from "../../lib/posts";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu allPostData={allPostsData} />
      <div className="content-holder">
        <h1>Blog</h1>

        <h3>general info</h3>

        <li>intro</li>
        <li>html tags</li>

        <h3>Next JS & React Routing</h3>
        <li>Choosing a right setup -- SPA or SSG</li>
        <li>Next project setup</li>
        <li>React Router</li>
        <li>React Project setup</li>
      </div>
    </>
  );
}
